### ISSUE TITLE
Wrong returned value

### ISSUE THREAD

**Issue by carpatin** [Mihai24/Evozon-Day3#7]
https://github.com/Mihai24/Evozon-Day3/blob/11f905af4cc7c031a17f992f0f272d7c62e172af/Queue/AdvancedQueue.php#L36
* You must return the dequeued value, not the remaining internal representation of the queue
* you add elements to a queue, then you get them out one by one in the exact order as they were added

**Comment by Mihai24** [comment]
Solved by returning de dequeued value.
